In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
#sentences
sent=['the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#defining vocabulary size
vocab_size=10000

In [10]:
#OHE representation
one_hot_rep=[one_hot(words,vocab_size) for words in sent]
one_hot_rep

[[8093, 6899, 4044, 4846],
 [8093, 6899, 4044, 8560],
 [8093, 8697, 4044, 822],
 [2408, 6304, 90, 8220, 6446],
 [2408, 6304, 90, 8220, 9491],
 [9434, 8093, 1761, 4044, 1071],
 [6584, 8503, 9764, 8220]]

In [11]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8093 6899 4044 4846]
 [   0    0    0    0 8093 6899 4044 8560]
 [   0    0    0    0 8093 8697 4044  822]
 [   0    0    0 2408 6304   90 8220 6446]
 [   0    0    0 2408 6304   90 8220 9491]
 [   0    0    0 9434 8093 1761 4044 1071]
 [   0    0    0    0 6584 8503 9764 8220]]


In [14]:
#feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 134ms/step


array([[[-3.88140455e-02,  4.92292531e-02,  1.63523667e-02,
         -3.59232202e-02,  6.54277951e-03,  2.19002105e-02,
         -2.30409261e-02,  1.16511956e-02, -3.77563722e-02,
         -1.43908970e-02],
        [-3.88140455e-02,  4.92292531e-02,  1.63523667e-02,
         -3.59232202e-02,  6.54277951e-03,  2.19002105e-02,
         -2.30409261e-02,  1.16511956e-02, -3.77563722e-02,
         -1.43908970e-02],
        [-3.88140455e-02,  4.92292531e-02,  1.63523667e-02,
         -3.59232202e-02,  6.54277951e-03,  2.19002105e-02,
         -2.30409261e-02,  1.16511956e-02, -3.77563722e-02,
         -1.43908970e-02],
        [-3.88140455e-02,  4.92292531e-02,  1.63523667e-02,
         -3.59232202e-02,  6.54277951e-03,  2.19002105e-02,
         -2.30409261e-02,  1.16511956e-02, -3.77563722e-02,
         -1.43908970e-02],
        [-4.30799238e-02, -4.36283275e-03, -4.08060923e-02,
         -1.75630935e-02,  3.82350124e-02,  2.95462944e-02,
          3.81311886e-02, -3.35293189e-02,  1.753668

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 8093, 6899, 4044, 4846])